import { SkillIR } from '../ir/types.js';

export class AntigravityGenerator {
  /**
   * Generates a fully compliant Google Antigravity Skill directory structure:
   * - SKILL.md (YAML frontmatter + markdown instructions)
   * - scripts/runner.mjs (Zero-dependency local execution runner)
   * - references/REFERENCE.md (Reference specifications)
   */
  static generate(ir: SkillIR): Record<string, string> {
    const files: Record<string, string> = {};
    const skillDir = `skills/${ir.name}`;

    // 1. Build SKILL.md
    const frontmatter = [
      '---',
      `name: ${ir.name}`,
      `description: ${ir.description.replace(/\n/g, ' ')}`,
      `version: ${ir.version}`,
      `category: ${ir.category}`,
      '---'
    ].join('\n');

    const toolsSection = ir.tools.map(tool => {
      const paramList = Object.entries(tool.parameters.properties)
        .map(([pName, pDef]) => `  - \`${pName}\` (${pDef.type}${tool.parameters.required?.includes(pName) ? ', required' : ', optional'}): ${pDef.description || 'No description'}`)
        .join('\n');

      return `### Tool: \`${tool.name}\`
**Risk Level**: \`${tool.riskLevel}\`  
**Description**: ${tool.description}

**Parameters**:
${paramList || '  *No parameters required*'}

${tool.guardrails?.requireConfirmation ? '> [!CAUTION]\n> This tool performs destructive mutations. Always simulate with `dryRun: true` or confirm explicitly.\n' : ''}
`;
    }).join('\n\n');

    const examplesSection = ir.examples.map(ex => {
      return `#### Scenario: ${ex.title}
**User**: "${ex.userPrompt}"  
**Action**:
\`\`\`json
${JSON.stringify(ex.expectedToolCalls, null, 2)}
\`\`\`
${ex.notes ? `*Note*: ${ex.notes}` : ''}
`;
    }).join('\n\n');

    const skillMd = `${frontmatter}

# ${ir.displayName}

${ir.description}

## Behavioral Instructions & Workflow
${ir.workflowInstructions}

## Safety & Guardrails
- **Path Traversal Protection**: All file path parameters are sandboxed to the project directory. Prohibited patterns (\`..\`, \`/etc\`, system roots) will abort execution immediately.
- **Destructive Mutation Gate**: Destructive write actions require explicit parameter confirmation (\`confirm: true\`) or dry-run validation (\`dryRun: true\`).
- **Credential & Secret Protection**: Parameters are deterministically scanned for raw API keys and private credentials; outputs are automatically redacted to prevent exfiltration into LLM context.
- **Timeout Policy**: Tools will terminate if execution exceeds ${ir.guardrails.defaultTimeoutSeconds} seconds.

## When to Trigger
This skill should be invoked when the user asks to:
${ir.triggerPhrases.map(tp => `- ${tp}`).join('\n')}

## Available Tools
${toolsSection}

## Reference Examples
${examplesSection || '*No examples provided*'}
`;

    files[`${skillDir}/SKILL.md`] = skillMd.trim() + '\n';

    // 2. Build scripts/runner.mjs
    const runnerScript = `#!/usr/bin/env node
/**
 * Auto-generated Antigravity Tool Runner for ${ir.name}
 * Generated by PolySkill Universal Compiler
 */

import { argv, exit } from 'node:process';

const toolName = argv[2];
const rawArgs = argv[3] || '{}';

if (!toolName) {
  console.error("Usage: node runner.mjs <tool_name> '<json_arguments>'");
  exit(1);
}

let args;
try {
  args = JSON.parse(rawArgs);
} catch (e) {
  console.error("[ERROR] Invalid JSON arguments:", e.message);
  exit(1);
}

// Runtime Guardrail Validation
for (const [key, value] of Object.entries(args)) {
  if (typeof value === 'string') {
    if (/\\.\\.[\\\\/]/i.test(value)) {
      console.error(\`[GUARDRAIL_BLOCKED] Path traversal attempt detected in '\${key}': \${value}\`);
      exit(2);
    }
    if (/(\\bAKIA[0-9A-Z]{16}\\b|\\bsk-[a-zA-Z0-9]{20,}\\b|\\bghp_[a-zA-Z0-9]{36}\\b|-----BEGIN (?:RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----)/.test(value)) {
      console.error(\`[GUARDRAIL_BLOCKED] Raw credential or secret detected in '\${key}'\`);
      exit(2);
    }
  }
}

console.log(JSON.stringify({
  status: "success",
  skill: "${ir.name}",
  executedTool: toolName,
  parameters: args,
  timestamp: new Date().toISOString(),
  message: \`Executed \${toolName} successfully via PolySkill runner.\`
}, null, 2));
`;

    files[`${skillDir}/scripts/runner.mjs`] = runnerScript.trim() + '\n';

    // 3. Build references/SPEC.md
    const specMd = `# ${ir.displayName} Technical Reference

- **Skill Name**: \`${ir.name}\`
- **Compiler Target**: Google Antigravity Skill
- **Compiled At**: ${ir.metadata.compiledAt}
- **Source Type**: \`${ir.metadata.sourceType}\`
- **Safety Score**: ${ir.metadata.safetyScore}/100

## Environment Variables
${(ir.envRequirements && ir.envRequirements.length > 0) ? ir.envRequirements.map(env => `- \`${env.name}\` (${env.required ? 'Required' : 'Optional'}): ${env.description}`).join('\n') : '*No custom environment variables required.*'}

## Tool Manifest
| Tool Name | Risk Level | Method/Type | Parameters |
|---|---|---|---|
${ir.tools.map(t => `| \`${t.name}\` | \`${t.riskLevel}\` | \`${t.execution.type}\` | ${Object.keys(t.parameters.properties).join(', ') || 'none'} |`).join('\n')}
`;

    files[`${skillDir}/references/SPEC.md`] = specMd.trim() + '\n';

    return files;
  }
}
