import { SkillIR } from '../ir/types.js';

export class CursorGenerator {
  /**
   * Generates high-density Cursor & Windsurf rules (.cursorrules / .windsurfrules)
   * tailored to the agent's context window.
   */
  static generate(ir: SkillIR): Record<string, string> {
    const files: Record<string, string> = {};
    const dir = `cursor/${ir.name}`;

    const rulesContent = `# ${ir.displayName} Agent Rules
# Generated by PolySkill Universal Compiler

You are an expert AI developer with access to the ${ir.displayName} operational toolset.

## Core Directives
${ir.workflowInstructions}

## Guardrails & Security Protocols
- DO NOT execute commands containing path traversals (e.g. '../', '..\\\\', system directories).
- For destructive tools (e.g., deletions, truncations, purges), always simulate with \`dryRun: true\` first or prompt the user explicitly for confirmation.
- Respect a default timeout limit of ${ir.guardrails.defaultTimeoutSeconds} seconds per invocation.

## Available Skill Tools & Signatures
${ir.tools.map(tool => {
  const params = Object.entries(tool.parameters.properties)
    .map(([k, v]) => `  - ${k}: ${v.type} (${v.description || 'required'})`)
    .join('\n');
  return `### \`${tool.name}\` (${tool.riskLevel})
${tool.description}
Parameters:
${params || '  (none)'}
`;
}).join('\n')}

## Trigger Phrases
When the user asks any of the following, invoke this skill:
${ir.triggerPhrases.map(tp => `- "${tp}"`).join('\n')}
`;

    files[`${dir}/.cursorrules`] = rulesContent.trim() + '\n';
    files[`${dir}/.windsurfrules`] = rulesContent.trim() + '\n';

    return files;
  }
}
